const experience = [
    {
        companyName: 'Ferrari Films',
        role: 'Web Content Manager',
        howLong: '2014 &mdash; 2016',
        id: 'ferrarifilms',
        link: 'http://www.ferrarifilms.com/',
        description: 'At Ferrari Films, my contributions included script writing, as well as the project management of most of our medical programs, from ensuring the content quality of our websites to tracking the timelines of video production.',
        skills: ['html5']
    },
    {
        companyName: 'General Assembly',
        role: 'Software Engineering Fellow/Part-time Instructor',
        howLong: '2016 &mdash; present',
        id: 'gastudent',
        link: 'https://generalassemb.ly/',
        description: 'As a fellow at General Assembly, I studied software engineering, which included building portfolio projects and providing assistance to my peers.',
        skills: ['html5', 'css3', 'javascript', 'jquery', 'git', 'nodejs', 'react', 'php', 'python', 'postgresql', 'mongodb']
    },
    {
        companyName: 'RE/MAX',
        role: 'Back-end Engineer',
        howLong: '2017 &mdash; 2019',
        id: 'remax',
        link: 'https://www.remax.com/',
        description: 'As a Team Lead at RE/MAX, I had the honor of maintaining, building, and coordinating features for the CRM product of nearly 40 independent real estate brokerages, as well as contributing to the new RE/MAX platform.',
        skills: [
            'html5',
            'css3',
            'javascript',
            'jquery',
            'vue',
            'git',
            'php',
            'laravel',
            'mysql',
            'docker',
            'kubernetes',
            'aws',
        ]
    },
    {
        companyName: 'General Assembly',
        role: 'Instructor Lead',
        howLong: '2019 &mdash; present',
        id: 'gainstructor',
        link: 'https://generalassemb.ly/',
        description: 'I have the privilege of helping students advance their programming skills significantly on their journey toward becoming professional software engineers. Besides teaching programming concepts, I\'ve also built projects and tools to demonstrate the mechanics of NodeJS, Django, and React.',
        skills: [
            'html5',
            'css3',
            'javascript',
            'jquery',
            'git',
            'react',
            'python',
            'django',
            'flask',
            'nodejs',
            'postgresql',
            'mongodb',
            'aws',
        ]
    },
];
